server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///C:/Users/SSAFY/Desktop/%EC%9D%B4%EC%BB%A4%EB%A8%B8%EC%8A%A4%20%EC%84%9C%EB%B9%84%EC%8A%A4/TIL/Spring%20Cloud%EB%A1%9C%20%EA%B0%9C%EB%B0%9C%ED%95%98%EB%8A%94%20MSA/E-commerce%20Service/git-local-repo


